summary_id: comorbidity_index_score
patient_or_sample: patient
#source_table_prod: cdsi_prod.cdm_idbw_impact_pipeline_prod.ddp_comorbidities_index_summary
source_table_dev: cdsi_eng_phi.cdm_eng_comorbidities.ddp_comorbidities_index_summary
key_column: MRN
columns:
- MRN
- NCI_SCORE
date_columns: []
dest_prod:
  catalog: cdsi_eng_phi
  schema: cdm_eng_cbioportal_etl
  volume_name: cdm_eng_cbioportal_etl_volume
  filename: comorbidity_index_score_summary.tsv
dest_dev:
  catalog: cdsi_eng_phi
  schema: cdm_eng_cbioportal_etl
  volume_name: cdm_eng_cbioportal_etl_volume_dev
  filename: comorbidity_index_score_summary.tsv
column_metadata:
  NCI_SCORE:
    label: NCI Comorbidity Score
    datatype: STRING
    comment: 'NCI Comorbidity Score ---DESCRIPTION: Final score for NCI comorbidity
      Index ---MISSING DATA: nan ---SOURCE: nan'
    fill_value: NA
