name: cdm-cbioportal-etl
channels:
  - conda-forge
  - bioconda
dependencies:
  - git
  - python=3.11
  - numpy=1.23.5
  - pyzmq=25.1.2
  - pip
  - pip:
      - git+https://github.com/callachennault/msk_cdm.git@python-refactor
      - git+https://github.com/clinical-data-mining/cdm-cbioportal-etl.git@config-file
