timeline_id: ecog_kps
source_table_prod: cdsi_prod.cdm_impact_pipeline_prod.t31_epic_ddp_ecog_kps
source_table_dev: cdsi_prod.cdm_impact_pipeline_prod.t31_epic_ddp_ecog_kps
output_filename: data_timeline_ecog_kps
patient_or_sample: patient
table_metadata:
  form_name: ECOG-KPS
  cdm_source_table: epic_ddp_concat/ecog_kps/impact/table_timeline_ecog_kps.tsv
  table_description: Timeline of KPS or ECOG values provided by patient
  cbio_timeline_reason_for_missing_data: No data in clindoc notes noting KPS or ECOG
    information to use regex to extract info.
  cbio_timeline_data_source: Derived from clindoc notes
  cbio_data_source_link: https://github.mskcc.org/cdsi/msk-impact/blob/master/msk_solid_heme/data_timeline_ecog.txt
  for_docs_site_timeline: true
columns:
  PATIENT_ID:
    field_name: PATIENT_ID
    field_label: PATIENT_ID
    field_note: Medical Record Number
    nlp_derived: false
  START_DATE:
    field_name: START_DATE
    field_label: Date of Clinical Note for ECOG
    field_note: Date of clinical note where ECOG is reported
    nlp_derived: false
  STOP_DATE:
    field_name: STOP_DATE
    field_label: Date of Clinical Note (DNU)
    field_note: DNU
    nlp_derived: false
  EVENT_TYPE:
    field_name: EVENT_TYPE
    field_label: Event Type for ECOG
    field_note: Event type, diagnosis
    nlp_derived: false
  SUBTYPE:
    field_name: SUBTYPE
    field_label: Subtype for ECOG
    field_note: Subtype, ECOG-KPS Score
    nlp_derived: false
  SOURCE:
    field_name: SOURCE
    field_label: Source of ECOG
    field_note: Source of output, clindoc notes or Epic
    nlp_derived: false
  ECOG_KPS:
    field_name: ECOG_KPS
    field_label: ECOG-KPS Score
    field_note: KPS or ECOG score. Values are standardized from 0-4, with 4 being
      the poorest self-reported status
    nlp_derived: false
