timeline_id: follow_up
source_table_prod: cdsi_eng_phi.cdm_eng_cbioportal_etl.data_timeline_follow_up
source_table_dev: cdsi_eng_phi.cdm_eng_cbioportal_etl.data_timeline_follow_up
output_filename: data_timeline_follow_up
patient_or_sample: patient
output_table:
  catalog: cdsi_eng_phi
  schema: cdm_eng_cbioportal_etl
table_metadata:
  form_name: Patient Follow-up
  cdm_source_table: epic_ddp_concat/demographics/table_timeline_follow_up.tsv
  table_description: Timeline of patient entry to MSK, last follow up, and death
  cbio_timeline_reason_for_missing_data: Date of death dependent if patient is deceased.
    MRN creation date and followup data should be complete.
  cbio_timeline_data_source: IDB, Patient demographics.
  cbio_data_source_link: https://github.mskcc.org/cdsi/msk-impact/blob/master/msk_solid_heme/data_timeline_follow_up.txt
  for_docs_site_timeline: true
columns:
  PATIENT_ID:
    field_name: PATIENT_ID
    field_label: PATIENT_ID
    field_note: Medical Record Number
    nlp_derived: false
  START_DATE:
    field_name: START_DATE
    field_label: 'Date of Hospital Entry, Follow-up, or Death '
    field_note: MRN create date, date of last follow-up, or date of death
    nlp_derived: false
  STOP_DATE:
    field_name: STOP_DATE
    field_label: Stop Date (Not used)
    field_note: All should be blank (Used for cbioportal etl purposes)
    nlp_derived: false
  EVENT_TYPE:
    field_name: EVENT_TYPE
    field_label: Event Type
    field_note: All should be under Diagnosis (portal track)
    nlp_derived: false
  SUBTYPE:
    field_name: SUBTYPE
    field_label: Subtype
    field_note: All should be Follow-up (portal sub track)
    nlp_derived: false
  SOURCE:
    field_name: SOURCE
    field_label: Event Name
    field_note: MRN create date, date of last follow-up, or date of death
    nlp_derived: false
