timeline_id: pdl1
source_table_prod: cdsi_prod.cdm_idbw_impact_pipeline_prod.table_timeline_pdl1_calls
source_table_dev: cdsi_eng_phi.cdm_eng_pathology_report_segmentation.table_timeline_pdl1_calls
output_filename: data_timeline_pdl1
patient_or_sample: patient
table_metadata:
  form_name: PD-L1 Positivity
  cdm_source_table: epic_ddp_concat/pathology/table_timeline_pdl1_calls.tsv
  table_description: NLP-derived PD-L1 calls from pathology reports
  cbio_timeline_reason_for_missing_data: No reported PD-L1 Score for patient. Rule-based
    NLP did not sense the word PD-L1 any pathology reports.
  cbio_timeline_data_source: NLP generated (Rule-based NLP) from surgical pathology
    reports
  cbio_data_source_link: https://github.mskcc.org/cdsi/msk-impact/blob/master/msk_solid_heme/data_timeline_pdl1.txt
  for_docs_site_timeline: true
columns:
  PATIENT_ID:
    field_name: PATIENT_ID
    field_label: PATIENT_ID
    field_note: Medical Record Number
    nlp_derived: false
  START_DATE:
    field_name: START_DATE
    field_label: Date of PD-L1 Score
    field_note: Date of report PD-L1 was measured
    nlp_derived: false
  STOP_DATE:
    field_name: STOP_DATE
    field_label: Date of PD-L1 Score (End, DNU)
    field_note: Do not use
    nlp_derived: false
  EVENT_TYPE:
    field_name: EVENT_TYPE
    field_label: Event Type for PD-L1 Score
    field_note: cbioportal column for place. Will be Diagnosis for now
    nlp_derived: false
  SUBTYPE:
    field_name: SUBTYPE
    field_label: Subtype for PD-L1
    field_note: cbioportal column for place. Will be PD-L1 for now
    nlp_derived: false
  SOURCE:
    field_name: SOURCE
    field_label: Source of PD-L1
    field_note: cbioportal column for place. Will be CDM for now
    nlp_derived: false
  PDL1_POSITIVE:
    field_name: PDL1_POSITIVE
    field_label: Indicator for PD-L1 Positive
    field_note: PD-L1 Yes/No derived from surgical pathology reports
    nlp_derived: true
